//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataCenter.DataBase
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DataCenterEntities : DbContext
    {
        private static DataCenterEntities _context;
        public DataCenterEntities()
            : base("name=DataCenterEntities")
        {
        }

        public static DataCenterEntities GetContext() 
        { 
            if(_context == null)
                _context = new DataCenterEntities();

             return _context;
        
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Адрес_сотрудника> Адрес_сотрудника { get; set; }
        public virtual DbSet<Вид_техники> Вид_техники { get; set; }
        public virtual DbSet<Город> Город { get; set; }
        public virtual DbSet<Должность> Должность { get; set; }
        public virtual DbSet<Дом> Дом { get; set; }
        public virtual DbSet<Клиент> Клиент { get; set; }
        public virtual DbSet<Ремонт> Ремонт { get; set; }
        public virtual DbSet<Сотрудник> Сотрудник { get; set; }
        public virtual DbSet<Тип_ремонта> Тип_ремонта { get; set; }
        public virtual DbSet<Улица> Улица { get; set; }
        public virtual DbSet<Устройство> Устройство { get; set; }
    }
}
