//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataCenter.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Адрес_сотрудника
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Адрес_сотрудника()
        {
            this.Сотрудник = new HashSet<Сотрудник>();
        }
    
        public int id_Адрес_сотрудника { get; set; }
        public Nullable<int> id_Город { get; set; }
        public Nullable<int> id_Улица { get; set; }
        public Nullable<int> id_Дом { get; set; }
    
        public virtual Город Город { get; set; }
        public virtual Дом Дом { get; set; }
        public virtual Улица Улица { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Сотрудник> Сотрудник { get; set; }
    }
}
