//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataCenter.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ремонт
    {
        public int id_Ремонт { get; set; }
        public Nullable<int> id_Устройство { get; set; }
        public Nullable<int> id_Тип_ремонта { get; set; }
        public Nullable<int> id_Сотрудник { get; set; }
        public Nullable<int> id_Клиент { get; set; }
        public Nullable<System.DateTime> Дата_начала { get; set; }
        public string Описание { get; set; }
        public Nullable<decimal> Стоимость { get; set; }
    
        public virtual Клиент Клиент { get; set; }
        public virtual Сотрудник Сотрудник { get; set; }
        public virtual Тип_ремонта Тип_ремонта { get; set; }
        public virtual Устройство Устройство { get; set; }
    }
}
