//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataCenter.DataBase
{
    using System;
    using System.Collections.Generic;
    
    public partial class Сотрудник
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Сотрудник()
        {
            this.Ремонт = new HashSet<Ремонт>();
        }
    
        public int id_Сотрудник { get; set; }
        public Nullable<int> id_Должность { get; set; }
        public Nullable<int> id_Адрес_сотрудника { get; set; }
        public string ФИО { get; set; }
        public string Телефон { get; set; }
        public string Почта { get; set; }
        public string Логин { get; set; }
        public string Пароль { get; set; }
        public Nullable<decimal> Зарплата { get; set; }
    
        public virtual Адрес_сотрудника Адрес_сотрудника { get; set; }
        public virtual Должность Должность { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ремонт> Ремонт { get; set; }
    }
}
